# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: find-faces.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='find-faces.proto',
  package='findFaces',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x66ind-faces.proto\x12\tfindFaces\"&\n\x07Picture\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\"7\n\x10\x46indFacesRequest\x12#\n\x07picture\x18\x01 \x01(\x0b\x32\x12.findFaces.Picture\"X\n\x11\x46indFacesResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12!\n\x05\x66\x61\x63\x65s\x18\x02 \x03(\x0b\x32\x12.findFaces.Picture\x12\x10\n\x08nb_faces\x18\x03 \x01(\x05\x32U\n\tFindFaces\x12H\n\tFindFaces\x12\x1b.findFaces.FindFacesRequest\x1a\x1c.findFaces.FindFacesResponse\"\x00\x62\x06proto3')
)




_PICTURE = _descriptor.Descriptor(
  name='Picture',
  full_name='findFaces.Picture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='findFaces.Picture.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='findFaces.Picture.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=69,
)


_FINDFACESREQUEST = _descriptor.Descriptor(
  name='FindFacesRequest',
  full_name='findFaces.FindFacesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='picture', full_name='findFaces.FindFacesRequest.picture', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=126,
)


_FINDFACESRESPONSE = _descriptor.Descriptor(
  name='FindFacesResponse',
  full_name='findFaces.FindFacesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='findFaces.FindFacesResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='faces', full_name='findFaces.FindFacesResponse.faces', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nb_faces', full_name='findFaces.FindFacesResponse.nb_faces', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=216,
)

_FINDFACESREQUEST.fields_by_name['picture'].message_type = _PICTURE
_FINDFACESRESPONSE.fields_by_name['faces'].message_type = _PICTURE
DESCRIPTOR.message_types_by_name['Picture'] = _PICTURE
DESCRIPTOR.message_types_by_name['FindFacesRequest'] = _FINDFACESREQUEST
DESCRIPTOR.message_types_by_name['FindFacesResponse'] = _FINDFACESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Picture = _reflection.GeneratedProtocolMessageType('Picture', (_message.Message,), dict(
  DESCRIPTOR = _PICTURE,
  __module__ = 'find_faces_pb2'
  # @@protoc_insertion_point(class_scope:findFaces.Picture)
  ))
_sym_db.RegisterMessage(Picture)

FindFacesRequest = _reflection.GeneratedProtocolMessageType('FindFacesRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINDFACESREQUEST,
  __module__ = 'find_faces_pb2'
  # @@protoc_insertion_point(class_scope:findFaces.FindFacesRequest)
  ))
_sym_db.RegisterMessage(FindFacesRequest)

FindFacesResponse = _reflection.GeneratedProtocolMessageType('FindFacesResponse', (_message.Message,), dict(
  DESCRIPTOR = _FINDFACESRESPONSE,
  __module__ = 'find_faces_pb2'
  # @@protoc_insertion_point(class_scope:findFaces.FindFacesResponse)
  ))
_sym_db.RegisterMessage(FindFacesResponse)



_FINDFACES = _descriptor.ServiceDescriptor(
  name='FindFaces',
  full_name='findFaces.FindFaces',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=218,
  serialized_end=303,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindFaces',
    full_name='findFaces.FindFaces.FindFaces',
    index=0,
    containing_service=None,
    input_type=_FINDFACESREQUEST,
    output_type=_FINDFACESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FINDFACES)

DESCRIPTOR.services_by_name['FindFaces'] = _FINDFACES

# @@protoc_insertion_point(module_scope)
